export PSQL_VERSION="10"
export MAIN_APP="form_instance"
export VERSION="12.0"
export TRAVIS_PYTHON_VERSION="3.6"
export ODOO_REPO="jarsa/odoo"
export ODOO_BRANCH="12.0"
export BASE_IMAGE="vauxoo/odoo-120-image"
export COUNTRY="MX"
