# -*- coding: utf-8 -*-
# Copyright 2019 JARSA Sistemas S.A. de C.V.
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl.html).

from odoo import _, api, fields, models
from odoo.exceptions import UserError


class SaleOrder(models.Model):
    _inherit = 'sale.order'

    master_sale_order = fields.Boolean(
        help='If you check this field, this sale order does not run any '
             'procurement and will be selectable when you request '
             'a product defined in this order.',
    )
    master_order_id = fields.Many2one(
        'sale.order', string="Master Sale Order",
        copy=False, ondelete='set null',
        help="Si esta orden fue creada desde una requisición de venta y enlazada a un pedido master, aquí queda ese enlace."
    )
    request_id = fields.Many2one(
        comodel_name='sale.request',
        string='Sale Request',
        copy=False,
        readonly=True,
    )

    master_sale_order_line = fields.One2many(
        comodel_name='sale.order.line',
        inverse_name='order_id',
        string="Master Sale Order Lines",
        copy=True, auto_join=True)

    @api.model
    def create(self, vals):
        if self._context.get('is_master_order'):
            vals['name'] = self.env['ir.sequence'].next_by_code('master.sale.order') or _('New')
        return super().create(vals)

    def action_cancel(self):
        for rec in self:
            if rec.master_sale_order and rec.order_line.mapped('child_ids'):
                raise UserError(_('Cannot cancel master with child lines.'))
        return super().action_cancel()

    def button_link_sale_order(self):
        return {
            'name': _('Link Sale Order'),
            'type': 'ir.actions.act_window',
            'res_model': 'link.sale.order.wizard',
            'view_mode': 'form',
            'target': 'new',
        }

    def button_child_sale_orders(self):
        self.ensure_one()
        child_ids = self.order_line.mapped('child_ids.order_id.id')
        return {
            'name': _('Child Sale Orders'),
            'type': 'ir.actions.act_window',
            'res_model': 'sale.order',
            'view_mode': 'tree,form',
            'domain': [('id', 'in', child_ids)],
            'context': {'create': False, 'delete': False},
        }

    def get_formview_id(self, access_uid=None):
        """Override to return unified view for both master and normal orders"""
        unified_view = self.env.ref('sale_request.view_sale_order_unified_form', raise_if_not_found=False)
        if unified_view:
            return unified_view.id
        return super().get_formview_id(access_uid)

    # -------------------------------
    # Parche para evitar el singleton
    # -------------------------------
    def _get_lang(self):
        """
        En Odoo 17 este método hace ensure_one() y a veces el wizard
        dispara un recálculo con order_id vacío. Aquí lo capturamos.
        """
        try:
            return super(SaleOrder, self)._get_lang()
        except ValueError:
            # Si no hay un order_id único, devolvemos el idioma del usuario
            return self.env.user.lang


class SaleOrderLine(models.Model):
    _inherit = 'sale.order.line'

    master_sale_order = fields.Boolean(
        related='order_id.master_sale_order',
        help='If you check this field, this sale order does not run any '
             'procurement and will be selectable when you request '
             'a product defined in this order.',
    )
    parent_id = fields.Many2one(
        comodel_name='sale.order.line',
        string='Parent Sale Order Line',
        copy=False,
        readonly=True,
        help='Parent sale order line (master sale order).'
    )
    child_ids = fields.One2many(
        comodel_name='sale.order.line',
        inverse_name='parent_id',
        string='Child Sale Order Lines',
        copy=False,
        readonly=True,
        help='Sale Order Lines generated by sale request linked to this line.'
    )
    request_line_id = fields.Many2one(
        comodel_name='sale.request.line',
        string='Sale Request',
        copy=False,
        ondelete='restrict',
    )
    product_uom_qty_total = fields.Float(
        string='Total Ordered Quantity',
        copy=False,
        compute='_compute_product_uom_qty_total',
        compute_sudo=True,
        store=True,
        digits='Product Unit of Measure',
    )
    qty_delivered_total = fields.Float(
        string='Total Delivered Quantity',
        copy=False,
        compute='_compute_qty_delivered_total',
        compute_sudo=True,
        store=True,
        digits='Product Unit of Measure',
    )
    qty_invoiced_total = fields.Float(
        string='Total Invoiced Quantity',
        copy=False,
        compute='_compute_qty_invoiced_total',
        compute_sudo=True,
        store=True,
        digits='Product Unit of Measure',
    )
    remaining_product_qty = fields.Float(
        string='Remaining Product Quantity',
        copy=False,
        compute='_compute_remaining_product_qty',
        compute_sudo=True,
        store=True,
        digits='Product Unit of Measure',
    )

    def write(self, values):
        return super().write(values)

    @api.depends('product_type', 'product_uom_qty', 'qty_delivered', 'state', 'move_ids', 'product_uom')
    def _compute_qty_to_deliver(self):
        # Excluimos master orders del cálculo de qty_to_deliver
        self2 = self
        for line in self:
            if line.order_id.master_sale_order:
                self2 -= line
                line.qty_to_deliver = 0
                line.display_qty_widget = False
        return super(SaleOrderLine, self2)._compute_qty_to_deliver()

    @api.depends('child_ids.product_uom_qty', 'child_ids.order_id.state')
    def _compute_product_uom_qty_total(self):
        for rec in self:
            rec.product_uom_qty_total = sum(rec.child_ids.filtered(
                lambda l: l.order_id.state != 'cancel').mapped('product_uom_qty'))

    @api.depends('product_uom_qty', 'product_uom_qty_total')
    def _compute_remaining_product_qty(self):
        for rec in self:
            rec.remaining_product_qty = rec.product_uom_qty - rec.product_uom_qty_total

    @api.depends('child_ids.qty_delivered', 'child_ids.order_id.state')
    def _compute_qty_delivered_total(self):
        for rec in self:
            rec.qty_delivered_total = sum(rec.child_ids.filtered(
                lambda l: l.order_id.state != 'cancel').mapped('qty_delivered'))

    @api.depends('child_ids.qty_invoiced', 'child_ids.order_id.state')
    def _compute_qty_invoiced_total(self):
        for rec in self:
            rec.qty_invoiced_total = sum(rec.child_ids.filtered(
                lambda l: l.order_id.state != 'cancel').mapped('qty_invoiced'))

    def _action_launch_stock_rule(self, previous_product_uom_qty=False):
        """ Override para evitar procurement en master orders """
        if all(self.mapped('order_id.master_sale_order')):
            return True
        return super()._action_launch_stock_rule(previous_product_uom_qty=previous_product_uom_qty)

    # -------------------------------------------------------------------------
    #  Este name_get evita el Expected singleton cuando order_id está vacío
    # -------------------------------------------------------------------------
    def name_get(self):
        result = []
        for line in self:
            # Si existe un pedido válido, respetamos la lógica original
            if line.order_id and line.order_id.name:
                # Tomamos la primera línea de descripción o el nombre del producto
                desc = (line.name or '').split('\n', 1)[0] or line.product_id.name
                display = '%s - %s' % (line.order_id.name, desc)
            else:
                # Fallback: sólo el display_name del producto
                display = line.product_id.display_name
            result.append((line.id, display))
        return result